### ISSUE TITLE
预测结果可视化

### ISSUE THREAD

**Issue by YEKAI-2022** [YoZhibo/ForecastGrapher#1]
![Uploading image.png…]()

你好，请问一下，上面的预测图时更具你提供的代码画出来的，怎么和论文中的差距有点大呢，是什么原因呀。这个实验是在ECL数据集上跑出的预测结果

**Comment by YEKAI-2022** [comment]
![Uploading 局部截取_20241025_143948.png…]()

**Comment by YEKAI-2022** [comment]
![Uploading 局部截取_20241025_143948.png…]()

**Comment by YEKAI-2022** [comment]
![Uploading 长截图_20240820_114311.png…]()

**Comment by YoZhibo** [comment]
您好，图片显示不出来。如果是代码中的绘图函数，是这个框架延续保留下来的，我们并没有直接使用它进行可视化。

**Comment by YEKAI-2022** [comment]
[image: image.png]
你好，感谢你的答复，我就是想请教一下你们这个图就是代码框架中test_result中生成的吗？为什么我复现后，差这么多。还是说你们有其他的办法画出的这个图


Wanlin Cai ***@***.***> 于2024年10月26日周六 10:52写道：

**Comment by YoZhibo** [comment]
您好，我们通过保存预测结果文件，使用plt进行绘制。由于文件较大，进行了注释，您可以简单修改 [save](https://github.com/YoZhibo/ForecastGrapher/blob/main/exp/exp_main.py#L303-L305) 。

**Comment by YEKAI-2022** [comment]
感谢您的回复，可以理解成论文中预测的可视化图片都是通过pred.npy和true.npy这两个文件画出来的吗？而不是直接使用在test_results中的PDF文件
但是使用下面代码画出的还有有偏差，代码中trues[:,1,-1]和preds[:,1,-1]索引这么写对吗？再次感谢您的解答，期待您的回复！
import numpy as np
import matplotlib.pyplot as plt
preds = np.load('pred.npy')
trues = np.load('true.npy')

plt.figure()
plt.plot (trues[:,1,-1], label='GroundTruth')
plt.plot (preds[:,1,-1], label='Prediction')
plt.legend()
plt.show()

Wanlin Cai ***@***.***> 于2024年10月29日周二 09:12写道：

**Comment by YoZhibo** [comment]
对的，使用npy文件进行绘制，如果需要显示输入部分，可以读取x.npy进行拼接。此外您可能要保留完整的时间维度，而不是截取单个时间点；并交换后两个维度的位置后再进行可视化。

**Comment by YEKAI-2022** [comment]
非常感谢您的解答，问题已经解决，再次表示感谢！

Wanlin Cai ***@***.***> 于2024年10月31日周四 17:40写道：
